### ISSUE TITLE
Phoenix watchers problem on Windows

### ISSUE THREAD

**Issue by MartinKavik** [carleryd/elm-hipster-stack#1]
Hi,
I've got same problem: https://github.com/phoenixframework/phoenix/issues/1218
Suggested solution is to change **config/dev.exs** (not tested on *nix):

**watchers: [{Path.expand("node_modules/webpack/bin/webpack.js"), ["--watch", "--colors", "--progress"]}]**

to

**watchers: [node: ["node_modules/webpack/bin/webpack.js", "--watch", "--colors", "--progress"]]**
## 

Everything else runs without problem on Windows 10 x64. Btw, I was looking for exactly this stack for my / maybe company's new projects, thank you.

**Comment by note89** [comment]
Hi! we have not updated this repo to follow the config that we are currently using but it's the same as yours with one difference. The `--cache=false` is because we had issues where a change to say `Model` in one component would not throw and error in the files using it. Or the other way around, get and error from something wanting the new model but saying that it gets the old one even thou it no longer exists. Not sure if this solves the issue completely but have not have any issues since we added it.

```
watchers: [node: ["node_modules/webpack/bin/webpack.js", "--watch", "--color", "--cache=false", "--progress"]]
```
